### ISSUE TITLE
Struktura projektu

### ISSUE THREAD

**Issue by krysz** [DevelopersOrganizationFork/monitor-front#1]
Panie Michale @mdrobny przepinam na Ciebie issue, wrzuć tak jak się umawialiśmy tę bazę co tam robisz.

**Comment by mdrobny** [comment]
Jest i struktura. Jak odpalić dałem opis w readme. 
Jest app.js, jest kontroler, template i service. 
Zrobiłem najprostszego mocka danych jakie będziemy dostawać z api:

``` javascript
sensors = [
                {
                    id: 0,
                    cpuUsage: 10,
                    ramUsage: 2100
                },
                {
                    id: 1,
                    cpuUsage: 89,
                    ramUsage: 5500
                }
            ];
```

Wyświetlają się więc działa.

**Comment by KamilSzelag** [comment]
Czy to issue jest jeszcze aktualne, ktoś nad nim pracuje ?
@mdrobny możesz napisać status tego zgłoszenia ?
