### ISSUE TITLE
Wyświetlanie listy hostów

### ISSUE THREAD

**Issue by mdrobny** [DevelopersOrganizationFork/monitor-front#2]
W postaci tabeli z której można wybrać interesującego nas hosta

**Comment by mdrobny** [comment]
Można by też wyświetlać w tej tabeli ostatni pomiar, tak żeby mieć porównanie z innymi sensorami

**Comment by krysz-clgx** [comment]
@mdrobny are you sure it was completed? ;)

**Comment by KamilSzelag** [comment]
wznawiamy projekt, mam coś do dorobienia tutaj ?

**Comment by mdrobny** [comment]
trzeba listę hostów wyświetlić i będzie gotowe, szybka sprawa, 5k loc, lecimy
